//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BranchType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BranchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employee" type="{http://www.example.org/cbrt}EmployeeType"/>
 *         &lt;element name="telNo" type="{http://www.example.org/cbrt}TelNoType"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="branchID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BranchType", propOrder = {

})
public class BranchType {

	@XmlElement(required = true)
	protected String branchName;
	@XmlElement(required = true)
	protected String branchLocation;
	@XmlElement(required = true)
	protected EmployeeType employee;
	@XmlElement(required = true)
	protected String telNo;
	@XmlElement(required = true)
	protected String address;
	@XmlAttribute(name = "branchID", required = true)
	protected String branchID;

	/**
	 * Gets the value of the branchName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchName() {
		return branchName;
	}

	/**
	 * Sets the value of the branchName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchName(String value) {
		this.branchName = value;
	}

	/**
	 * Gets the value of the branchLocation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchLocation() {
		return branchLocation;
	}

	/**
	 * Sets the value of the branchLocation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchLocation(String value) {
		this.branchLocation = value;
	}

	/**
	 * Gets the value of the employee property.
	 * 
	 * @return possible object is {@link EmployeeType }
	 * 
	 */
	public EmployeeType getEmployee() {
		return employee;
	}

	/**
	 * Sets the value of the employee property.
	 * 
	 * @param value
	 *            allowed object is {@link EmployeeType }
	 * 
	 */
	public void setEmployee(EmployeeType value) {
		this.employee = value;
	}

	/**
	 * Gets the value of the telNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTelNo() {
		return telNo;
	}

	/**
	 * Sets the value of the telNo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTelNo(String value) {
		this.telNo = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAddress(String value) {
		this.address = value;
	}

	/**
	 * Gets the value of the branchID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchID() {
		return branchID;
	}

	/**
	 * Sets the value of the branchID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchID(String value) {
		this.branchID = value;
	}

	@Override
	public String toString() {
		return "BranchType [" + (branchName != null ? "branchName=" + branchName + ", " : "")
				+ (branchLocation != null ? "branchLocation=" + branchLocation + ", " : "")
				+ (employee != null ? "employee=" + employee + ", " : "")
				+ (telNo != null ? "telNo=" + telNo + ", " : "") + (address != null ? "address=" + address + ", " : "")
				+ (branchID != null ? "branchID=" + branchID : "") + "]\r\n";
	}

}
