//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//


package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CbrtObjectiveType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CbrtObjectiveType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value=" To achieve and maintain price stability"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CbrtObjectiveType")
@XmlEnum
public enum CbrtObjectiveType {

    @XmlEnumValue(" To achieve and maintain price stability")
    TO_ACHIEVE_AND_MAINTAIN_PRICE_STABILITY(" To achieve and maintain price stability");
    private final String value;

    CbrtObjectiveType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CbrtObjectiveType fromValue(String v) {
        for (CbrtObjectiveType c: CbrtObjectiveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
