//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for cbrtType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="cbrtType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Governor" type="{http://www.example.org/cbrt}GovernorType"/>
 *         &lt;element name="DeputyGovernor" type="{http://www.example.org/cbrt}DeputyGovernorType" maxOccurs="4"/>
 *         &lt;element name="MPC_member" type="{http://www.example.org/cbrt}MPC_memberType" maxOccurs="6"/>
 *         &lt;element name="BoardMember" type="{http://www.example.org/cbrt}BoardMemberType" maxOccurs="7"/>
 *         &lt;element name="AuditCommunityMember" type="{http://www.example.org/cbrt}AuditComMemberType" maxOccurs="4"/>
 *         &lt;element name="ExecCommunityMember" type="{http://www.example.org/cbrt}ExecComMemberType" maxOccurs="5"/>
 *         &lt;element name="Client" type="{http://www.example.org/cbrt}ClientType" maxOccurs="unbounded"/>
 *         &lt;element name="ShareHolder" type="{http://www.example.org/cbrt}ShareHolderType" maxOccurs="unbounded"/>
 *         &lt;element name="Branch" type="{http://www.example.org/cbrt}BranchType" maxOccurs="unbounded"/>
 *         &lt;element name="Employee" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Contractual" type="{http://www.example.org/cbrt}ContractualEmployeeType"/>
 *                   &lt;element name="Regular" type="{http://www.example.org/cbrt}RegularEmployeeType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cbrtType", propOrder = { "governor", "deputyGovernor", "mpcMember", "boardMember",
		"auditCommunityMember", "execCommunityMember", "client", "shareHolder", "branch", "employee" })
public class CbrtType {

	@XmlElement(name = "Governor", required = true)
	protected GovernorType governor;
	@XmlElement(name = "DeputyGovernor", required = true)
	protected List<DeputyGovernorType> deputyGovernor;
	@XmlElement(name = "MPC_member", required = true)
	protected List<MPCMemberType> mpcMember;
	@XmlElement(name = "BoardMember", required = true)
	protected List<BoardMemberType> boardMember;
	@XmlElement(name = "AuditCommunityMember", required = true)
	protected List<AuditComMemberType> auditCommunityMember;
	@XmlElement(name = "ExecCommunityMember", required = true)
	protected List<ExecComMemberType> execCommunityMember;
	@XmlElement(name = "Client", required = true)
	protected List<ClientType> client;
	@XmlElement(name = "ShareHolder", required = true)
	protected List<ShareHolderType> shareHolder;
	@XmlElement(name = "Branch", required = true)
	protected List<BranchType> branch;
	@XmlElement(name = "Employee", required = true)
	protected List<CbrtType.Employee> employee;

	/**
	 * Gets the value of the governor property.
	 * 
	 * @return possible object is {@link GovernorType }
	 * 
	 */
	public GovernorType getGovernor() {
		return governor;
	}

	/**
	 * Sets the value of the governor property.
	 * 
	 * @param value
	 *            allowed object is {@link GovernorType }
	 * 
	 */
	public void setGovernor(GovernorType value) {
		this.governor = value;
	}

	/**
	 * Gets the value of the deputyGovernor property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deputyGovernor property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeputyGovernor().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DeputyGovernorType }
	 * 
	 * 
	 */
	public List<DeputyGovernorType> getDeputyGovernor() {
		if (deputyGovernor == null) {
			deputyGovernor = new ArrayList<DeputyGovernorType>();
		}
		return this.deputyGovernor;
	}

	/**
	 * Gets the value of the mpcMember property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the mpcMember property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMPCMember().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MPCMemberType }
	 * 
	 * 
	 */
	public List<MPCMemberType> getMPCMember() {
		if (mpcMember == null) {
			mpcMember = new ArrayList<MPCMemberType>();
		}
		return this.mpcMember;
	}

	/**
	 * Gets the value of the boardMember property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the boardMember property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBoardMember().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BoardMemberType }
	 * 
	 * 
	 */
	public List<BoardMemberType> getBoardMember() {
		if (boardMember == null) {
			boardMember = new ArrayList<BoardMemberType>();
		}
		return this.boardMember;
	}

	/**
	 * Gets the value of the auditCommunityMember property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the auditCommunityMember property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAuditCommunityMember().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AuditComMemberType }
	 * 
	 * 
	 */
	public List<AuditComMemberType> getAuditCommunityMember() {
		if (auditCommunityMember == null) {
			auditCommunityMember = new ArrayList<AuditComMemberType>();
		}
		return this.auditCommunityMember;
	}

	/**
	 * Gets the value of the execCommunityMember property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the execCommunityMember property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExecCommunityMember().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExecComMemberType }
	 * 
	 * 
	 */
	public List<ExecComMemberType> getExecCommunityMember() {
		if (execCommunityMember == null) {
			execCommunityMember = new ArrayList<ExecComMemberType>();
		}
		return this.execCommunityMember;
	}

	/**
	 * Gets the value of the client property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the client property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getClient().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ClientType }
	 * 
	 * 
	 */
	public List<ClientType> getClient() {
		if (client == null) {
			client = new ArrayList<ClientType>();
		}
		return this.client;
	}

	/**
	 * Gets the value of the shareHolder property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the shareHolder property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getShareHolder().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ShareHolderType }
	 * 
	 * 
	 */
	public List<ShareHolderType> getShareHolder() {
		if (shareHolder == null) {
			shareHolder = new ArrayList<ShareHolderType>();
		}
		return this.shareHolder;
	}

	/**
	 * Gets the value of the branch property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the branch property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBranch().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BranchType }
	 * 
	 * 
	 */
	public List<BranchType> getBranch() {
		if (branch == null) {
			branch = new ArrayList<BranchType>();
		}
		return this.branch;
	}

	/**
	 * Gets the value of the employee property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the employee property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEmployee().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CbrtType.Employee }
	 * 
	 * 
	 */
	public List<CbrtType.Employee> getEmployee() {
		if (employee == null) {
			employee = new ArrayList<CbrtType.Employee>();
		}
		return this.employee;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;choice>
	 *         &lt;element name="Contractual" type="{http://www.example.org/cbrt}ContractualEmployeeType"/>
	 *         &lt;element name="Regular" type="{http://www.example.org/cbrt}RegularEmployeeType"/>
	 *       &lt;/choice>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "contractual", "regular" })
	public static class Employee {

		@XmlElement(name = "Contractual")
		protected ContractualEmployeeType contractual;
		@XmlElement(name = "Regular")
		protected RegularEmployeeType regular;

		/**
		 * Gets the value of the contractual property.
		 * 
		 * @return possible object is {@link ContractualEmployeeType }
		 * 
		 */
		public ContractualEmployeeType getContractual() {
			return contractual;
		}

		/**
		 * Sets the value of the contractual property.
		 * 
		 * @param value
		 *            allowed object is {@link ContractualEmployeeType }
		 * 
		 */
		public void setContractual(ContractualEmployeeType value) {
			this.contractual = value;
		}

		/**
		 * Gets the value of the regular property.
		 * 
		 * @return possible object is {@link RegularEmployeeType }
		 * 
		 */
		public RegularEmployeeType getRegular() {
			return regular;
		}

		/**
		 * Sets the value of the regular property.
		 * 
		 * @param value
		 *            allowed object is {@link RegularEmployeeType }
		 * 
		 */
		public void setRegular(RegularEmployeeType value) {
			this.regular = value;
		}

	}

	@Override
	public String toString() {
		return "CbrtType [" + (governor != null ? "governor=" + governor + ",\r\n " : "")
				+ (deputyGovernor != null ? "deputyGovernor=" + deputyGovernor + ",\r\n " : "")
				+ (mpcMember != null ? "mpcMember=" + mpcMember + ",\r\n " : "")
				+ (boardMember != null ? "boardMember=" + boardMember + ",\r\n " : "")
				+ (auditCommunityMember != null ? "auditCommunityMember=" + auditCommunityMember + ",\r\n " : "")
				+ (execCommunityMember != null ? "execCommunityMember=" + execCommunityMember + ",\r\n " : "")
				+ (client != null ? "client=" + client + ", \r\n" : "")
				+ (shareHolder != null ? "shareHolder=" + shareHolder + ",\r\n " : "")
				+ (branch != null ? "branch=" + branch + ", \r\n" : "")
				+ (employee != null ? "employee=" + employee.toString() : "") + "]";
	}

}
