//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ClientType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ClientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Person" type="{http://www.example.org/cbrt}PersonType"/>
 *         &lt;element name="Company" type="{http://www.example.org/cbrt}CompanyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientType", propOrder = { "person", "company" })
public class ClientType {

	@XmlElement(name = "Person")
	protected PersonType person;
	@XmlElement(name = "Company")
	protected CompanyType company;

	/**
	 * Gets the value of the person property.
	 * 
	 * @return possible object is {@link PersonType }
	 * 
	 */
	public PersonType getPerson() {
		return person;
	}

	/**
	 * Sets the value of the person property.
	 * 
	 * @param value
	 *            allowed object is {@link PersonType }
	 * 
	 */
	public void setPerson(PersonType value) {
		this.person = value;
	}

	/**
	 * Gets the value of the company property.
	 * 
	 * @return possible object is {@link CompanyType }
	 * 
	 */
	public CompanyType getCompany() {
		return company;
	}

	/**
	 * Sets the value of the company property.
	 * 
	 * @param value
	 *            allowed object is {@link CompanyType }
	 * 
	 */
	public void setCompany(CompanyType value) {
		this.company = value;
	}

	@Override
	public String toString() {
		return "ClientType [" + (person != null ? "person=" + person + ", " : "")
				+ (company != null ? "company=" + company : "") + "]\r\n";
	}

}
