//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ContractualEmployeeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ContractualEmployeeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/cbrt}EmployeeType">
 *       &lt;sequence>
 *         &lt;element name="ContractExpDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractualEmployeeType", propOrder = { "contractExpDate" })
public class ContractualEmployeeType extends EmployeeType {

	@XmlElement(name = "ContractExpDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar contractExpDate;

	/**
	 * Gets the value of the contractExpDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getContractExpDate() {
		return contractExpDate;
	}

	/**
	 * Sets the value of the contractExpDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setContractExpDate(XMLGregorianCalendar value) {
		this.contractExpDate = value;
	}

	@Override
	public String toString() {
		return "ContractualEmployeeType ["
				+ (contractExpDate != null ? "contractExpDate=" + contractExpDate + ", " : "")
				+ (title != null ? "title=" + title + ", " : "")
				+ (assignmentDate != null ? "assignmentDate=" + assignmentDate + ", " : "")
				+ (employeeNumber != null ? "employeeNumber=" + employeeNumber + ", " : "")
				+ (firstName != null ? "firstName=" + firstName + ", " : "")
				+ (middleName != null ? "middleName=" + middleName + ", " : "")
				+ (lastName != null ? "lastName=" + lastName + ", " : "") + (ssn != null ? "ssn=" + ssn : "") + "]\r\n";
	}

}
