//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for EmployeeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/cbrt}PersonType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.example.org/cbrt}TitleType"/>
 *         &lt;element name="AssignmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EmployeeNumber" use="required" type="{http://www.example.org/cbrt}EmployeeNumberType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeType", propOrder = { "title", "assignmentDate" })
@XmlSeeAlso({ AuditComMemberType.class, ContractualEmployeeType.class, GovernorType.class, DeputyGovernorType.class,
		ExecComMemberType.class, RegularEmployeeType.class })
public class EmployeeType extends PersonType {

	@XmlElement(name = "Title", required = true)
	@XmlSchemaType(name = "string")
	protected TitleType title;
	@XmlElement(name = "AssignmentDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar assignmentDate;
	@XmlAttribute(name = "EmployeeNumber", required = true)
	protected BigInteger employeeNumber;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link TitleType }
	 * 
	 */
	public TitleType getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link TitleType }
	 * 
	 */
	public void setTitle(TitleType value) {
		this.title = value;
	}

	/**
	 * Gets the value of the assignmentDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAssignmentDate() {
		return assignmentDate;
	}

	/**
	 * Sets the value of the assignmentDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAssignmentDate(XMLGregorianCalendar value) {
		this.assignmentDate = value;
	}

	/**
	 * Gets the value of the employeeNumber property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getEmployeeNumber() {
		return employeeNumber;
	}

	/**
	 * Sets the value of the employeeNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setEmployeeNumber(BigInteger value) {
		this.employeeNumber = value;
	}

	@Override
	public String toString() {
		return "EmployeeType [" + (title != null ? "title=" + title + ", " : "")
				+ (assignmentDate != null ? "assignmentDate=" + assignmentDate + ", " : "")
				+ (employeeNumber != null ? "employeeNumber=" + employeeNumber + ", " : "")
				+ (firstName != null ? "firstName=" + firstName + ", " : "")
				+ (middleName != null ? "middleName=" + middleName + ", " : "")
				+ (lastName != null ? "lastName=" + lastName + ", " : "") + (ssn != null ? "ssn=" + ssn : "") + "]\r\n";
	}

}
