//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//


package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GovernorGraduateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GovernorGraduateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Economics"/>
 *     &lt;enumeration value="Econometrics"/>
 *     &lt;enumeration value="Banking"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GovernorGraduateType")
@XmlEnum
public enum GovernorGraduateType {

    @XmlEnumValue("Economics")
    ECONOMICS("Economics"),
    @XmlEnumValue("Econometrics")
    ECONOMETRICS("Econometrics"),
    @XmlEnumValue("Banking")
    BANKING("Banking");
    private final String value;

    GovernorGraduateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GovernorGraduateType fromValue(String v) {
        for (GovernorGraduateType c: GovernorGraduateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
