//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//

package tr.gov.cbrt.hwXml.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GovernorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GovernorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/cbrt}EmployeeType">
 *       &lt;sequence>
 *         &lt;element name="Graduate" type="{http://www.example.org/cbrt}GovernorGraduateType"/>
 *         &lt;element name="AssignmentCount" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GovernorType", propOrder = { "graduate", "assignmentCount" })
public class GovernorType extends EmployeeType {

	@XmlElement(name = "Graduate", required = true)
	@XmlSchemaType(name = "string")
	protected GovernorGraduateType graduate;
	@XmlElement(name = "AssignmentCount", required = true)
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger assignmentCount;

	/**
	 * Gets the value of the graduate property.
	 * 
	 * @return possible object is {@link GovernorGraduateType }
	 * 
	 */
	public GovernorGraduateType getGraduate() {
		return graduate;
	}

	/**
	 * Sets the value of the graduate property.
	 * 
	 * @param value
	 *            allowed object is {@link GovernorGraduateType }
	 * 
	 */
	public void setGraduate(GovernorGraduateType value) {
		this.graduate = value;
	}

	/**
	 * Gets the value of the assignmentCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getAssignmentCount() {
		return assignmentCount;
	}

	/**
	 * Sets the value of the assignmentCount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setAssignmentCount(BigInteger value) {
		this.assignmentCount = value;
	}

	@Override
	public String toString() {
		return "GovernorType [" + (graduate != null ? "graduate=" + graduate + ", " : "")
				+ (assignmentCount != null ? "assignmentCount=" + assignmentCount + ", " : "")
				+ (title != null ? "title=" + title + ", " : "")
				+ (assignmentDate != null ? "assignmentDate=" + assignmentDate + ", " : "")
				+ (employeeNumber != null ? "employeeNumber=" + employeeNumber + ", " : "")
				+ (firstName != null ? "firstName=" + firstName + ", " : "")
				+ (middleName != null ? "middleName=" + middleName + ", " : "")
				+ (lastName != null ? "lastName=" + lastName + ", " : "") + (ssn != null ? "ssn=" + ssn : "") + "]\r\n";
	}

}
