//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//


package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.gov.cbrt.hwXml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cbrt_QNAME = new QName("http://www.example.org/cbrt", "cbrt");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.gov.cbrt.hwXml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CbrtType }
     * 
     */
    public CbrtType createCbrtType() {
        return new CbrtType();
    }

    /**
     * Create an instance of {@link MPCMemberType }
     * 
     */
    public MPCMemberType createMPCMemberType() {
        return new MPCMemberType();
    }

    /**
     * Create an instance of {@link AuditComMemberType }
     * 
     */
    public AuditComMemberType createAuditComMemberType() {
        return new AuditComMemberType();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public ClientType createClientType() {
        return new ClientType();
    }

    /**
     * Create an instance of {@link ContractualEmployeeType }
     * 
     */
    public ContractualEmployeeType createContractualEmployeeType() {
        return new ContractualEmployeeType();
    }

    /**
     * Create an instance of {@link GovernorType }
     * 
     */
    public GovernorType createGovernorType() {
        return new GovernorType();
    }

    /**
     * Create an instance of {@link DeputyGovernorType }
     * 
     */
    public DeputyGovernorType createDeputyGovernorType() {
        return new DeputyGovernorType();
    }

    /**
     * Create an instance of {@link BranchType }
     * 
     */
    public BranchType createBranchType() {
        return new BranchType();
    }

    /**
     * Create an instance of {@link ShareHolderType }
     * 
     */
    public ShareHolderType createShareHolderType() {
        return new ShareHolderType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link BoardMemberType }
     * 
     */
    public BoardMemberType createBoardMemberType() {
        return new BoardMemberType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link ExecComMemberType }
     * 
     */
    public ExecComMemberType createExecComMemberType() {
        return new ExecComMemberType();
    }

    /**
     * Create an instance of {@link RegularEmployeeType }
     * 
     */
    public RegularEmployeeType createRegularEmployeeType() {
        return new RegularEmployeeType();
    }

    /**
     * Create an instance of {@link CbrtType.Employee }
     * 
     */
    public CbrtType.Employee createCbrtTypeEmployee() {
        return new CbrtType.Employee();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CbrtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/cbrt", name = "cbrt")
    public JAXBElement<CbrtType> createCbrt(CbrtType value) {
        return new JAXBElement<CbrtType>(_Cbrt_QNAME, CbrtType.class, null, value);
    }

}
