//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 10:22:26 AM EEST 
//


package tr.gov.cbrt.hwXml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShareHolderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShareHolderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="A_type" type="{http://www.example.org/cbrt}CompanyType"/>
 *         &lt;element name="B_type" type="{http://www.example.org/cbrt}CompanyType"/>
 *         &lt;element name="C_type" type="{http://www.example.org/cbrt}CompanyType"/>
 *         &lt;element name="D_type" type="{http://www.example.org/cbrt}PersonType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShareHolderType", propOrder = {
    "aType",
    "bType",
    "cType",
    "dType"
})
public class ShareHolderType {

    @XmlElement(name = "A_type")
    protected CompanyType aType;
    @XmlElement(name = "B_type")
    protected CompanyType bType;
    @XmlElement(name = "C_type")
    protected CompanyType cType;
    @XmlElement(name = "D_type")
    protected PersonType dType;

    /**
     * Gets the value of the aType property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyType }
     *     
     */
    public CompanyType getAType() {
        return aType;
    }

    /**
     * Sets the value of the aType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyType }
     *     
     */
    public void setAType(CompanyType value) {
        this.aType = value;
    }

    /**
     * Gets the value of the bType property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyType }
     *     
     */
    public CompanyType getBType() {
        return bType;
    }

    /**
     * Sets the value of the bType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyType }
     *     
     */
    public void setBType(CompanyType value) {
        this.bType = value;
    }

    /**
     * Gets the value of the cType property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyType }
     *     
     */
    public CompanyType getCType() {
        return cType;
    }

    /**
     * Sets the value of the cType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyType }
     *     
     */
    public void setCType(CompanyType value) {
        this.cType = value;
    }

    /**
     * Gets the value of the dType property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getDType() {
        return dType;
    }

    /**
     * Sets the value of the dType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setDType(PersonType value) {
        this.dType = value;
    }

	@Override
	public String toString() {
		return "ShareHolderType [" + (aType != null ? "aType=" + aType + ", " : "")
				+ (bType != null ? "bType=" + bType + ", " : "") + (cType != null ? "cType=" + cType + ", " : "")
				+ (dType != null ? "dType=" + dType : "") + "]\r\n";
	}

}
